### PR TITLE
nitpick: avoid some warnings

### PR DESCRIPTION
**Pull request by Martoni**
Just for a clean make ;)

### CODE REVIEW

**Comment by rofl0r** [comment]
i don't think commenting out big portions of the code is acceptable just to avoid some warnings. especially not in the way you did it, commenting out every single line with C++-style comment, when you could just as well have used C-style block comments (`/* ... */`) or even `#if 0 ... #endif`

**Comment by Martoni** [comment]
I added a commit just to replace C++ style comment by  `#if 0 ... #endif `

**Comment by veprbl** [comment]
Now you could squash the changes for ease of review and this PR is will be ready to rot for eternity! :)

**Comment by Martoni** [comment]
Ok I re-wrote the pull requests.

**Pull request closed without merging**
